############# French navigation ##############
# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Join us"
url = "join-us/"
weight = 2

# [[main]]
# name = "Services"
# url = "services/"
# weight = 3

[[main]]
name = "Team"
url = "team/"
weight = 3

[[main]]
name = "Blog"
url = "blog/"
weight = 4

# [[main]]
# name = "Contact"
# url = "contact/"
# weight = 5

[[main]]
name = "More"
weight = 5
hasChildren = true

  [[main]]
  parent = "More"
  name = "Meetings"
  url = "meetings/"

  
  [[main]]
  parent = "More"
  name = "Testimonial"
  url = "testimonial/"
  
  [[main]]
  parent = "More"
  name = "Faq"
  url = "faq/"