#################### default parameters ################################
# favicon
# favicon = "images/favicon.png"
# favicon_32x32 = "images/favicon.png"
# favicon_16x16 = "images/favicon.png"
# apple_touch_icon = "images/favicon.png"
# logo
logo_text = "STC"
# logo = "images/logo.png"
logo_width = ""
# OpenGraph / Twitter Card metadata
description = "Singtel Toastmasters Club"
author = "Themefisher"
# image = "images/logo.png" # this image will be used as fallback if a page has no image of its own
# contact form action
contact_form_action = "#" # contact form works with https://formspree.io
# custom script on header
custom_script= ""

[navigation_button_linked]
enable = true
label = "Member Log In"
link = "https://www.stclub.site/members/login.html"


# cookies
[cookies]
enable = false
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"